application: euchreblitz
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /images
  static_dir: images
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /.*
  script: index.app

libraries:
- name: jinja2
  version: latest
